### PR TITLE
Initial scaffolding of the app

### PR DESCRIPTION
**Pull request by ron2911**
This PR adds the basic scaffolding for the app. I have also added standardjs to the app.

### CODE REVIEW

**Comment by bomattin** [comment]
Might add `.idea` and `.DS_Store` to `.gitignore`. Other than that, looks good. +1

**Comment by ZacharySaunders** [comment]
I do agree with @bomattin here, we should add .idea and .DS_Store to .gitignore. Once that is complete, I will approve and the code can be pushed to master. Nice work!

**Comment by ZacharyDavidSaunders** [comment]
I do agree with @bomattin here, we should add .idea and .DS_Store to .gitignore. Once that is complete, I will approve and the code can be pushed to master. Nice work!

**Comment by bomattin** [comment]
+1

**Pull request merged**
